name: Build posts index

on:
  push:
    branches: [ main ]
    paths:
      - 'content/posts/**/*.md'
      - 'content/posts/**/*.jpg'
      - 'content/posts/**/*.jpeg'
      - 'content/posts/**/*.png'
      - 'content/posts/**/*.webp'
      - 'scripts/build-index.js'
  workflow_dispatch: {}

jobs:
  build-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build index.json from markdown
        run: node scripts/build-index.js

      - name: Commit updated index.json
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add content/posts/index.json
            git commit -m "chore(content): rebuild posts index [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi


